# networks:
#   default:
#     external:
#       name: ${NETWORK_NAME}

services:
  redis_queue:
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    image: redis:7.2.2
    expose:
      - 6379
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis-pda:/data

volumes:
  redis-pda:
    driver: local
